### PR TITLE
PyPI Packaging

### PR DESCRIPTION
**Pull request by kavinvin**

### CODE REVIEW

**Comment by klieret** [comment]
I'll move the config and data folders inside the rtk-lookup folder, else they'll be installed as their own packages

**Review by klieret — APPROVED** [review]
I'm happy to merge like this and would push to pypi once its merged. 

Do you want to add anything to this PR? @kavinvin  (and thank you so much for your work btw!!)

**Comment by kavinvin** [comment]
@klieret Thanks! I think this is okay for now. I’ll merge then.

**Comment by klieret** [comment]
Thank you! The whole thing should now be installable with ``pip3 install rtk-lookup``

**Pull request merged**
